---
- name: Get username
  become: false
  shell:
    cmd: whoami
  register: user

- name: Set home username
  set_fact:
    username: "{{ user.stdout }}"

- name: show username
  become: false
  debug: var=username

- name: Obtaining project from github
  git:
    clone: true
    repo: "{{ app_repository }}"
    dest: "/home/{{ username }}/{{  app_destination  }}"
    force: true

- name: Show dir
  shell:
    chdir: "/home/{{ username }}/{{  app_destination  }}"
    cmd: ls

- name: Install packages
  shell:
    chdir: "/home/{{ username }}/{{  app_destination  }}"
    cmd: "npm install"

- name: Switch to prod mode
  lineinfile:
    path: "/home/{{ username }}/{{ app_destination }}/.env"
    regexp: "PROD=false"
    line: "PROD=true"
    state: present
...
