---
- name: Start docker
  service:
    name: "docker"
    state: started

- name: pulling image
  docker_image:
    name: node
    tag: latest
    source: pull

- name: Obtaining project from github
  git: clone=true repo={{ app_repository }} dest={{  app_destination  }}


- name: Show dir
  shell: 
    chdir: "~/{{ app_destination }}" 
    cmd: ls

- name: install packages
  shell: 
    chdir: "~/{{ app_destination }}" 
    cmd: "npm install"

- name: start container
  docker_container:
    name: App_server
    image: node:latest
    state: started
    exposed_ports:
      - "{{ container_port }}"
    ports:
      - "{{ container_port }}:{{ app_port }}"
    volumes:
      - "{{ app_destination }}:/usr/local/app"
    working_dir: /usr/local/app
    command:
      - npm run start
...