---
- name: pulling image
  docker_image:
    name: idrissduval/catalogue
    source: pull

- name: start app inside a container
  docker_container:
    name: catalogue
    image: idrissduval/catalogue
    state: started
    ports:
      - "8223:8000"
...
